name: Run all tox jobs using Python3

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        min_versions: ["min_versions", "latest_versions"]
        exclude:
          - min_versions: "min_versions"
        include:
          - python-version: "3.7"
            min_versions: "min_versions"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get current month
      id: date
      run: echo "date=$(date +'%Y-%m')" >> $GITHUB_OUTPUT
    - name: Cache APT Packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libhdf5-dev
        version: 1.0
        execute_install_scripts: true
    - name: Cache tox and precommit environments
      uses: actions/cache@v3
      with:
        path: |
          .tox
          ~/.cache/pre-commit
        key: ${{ runner.os }}-${{ matrix.python-version }}-${{ steps.date.outputs.date }}-${{ hashFiles('setup.py') }}-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Clear results in tox environments
      run: |
        rm -rf .tox/*/tmp
    - name: Run tox with latest versions
      if: ${{ matrix.min_versions == 'latest_versions' }}
      run: |
        python -m pip install --upgrade pip setuptools
        pip install tox-gh-actions
        tox
    - name: Run tox with min versions
      if: ${{ matrix.min_versions == 'min_versions' }}
      run: |
        python -m pip install --upgrade pip setuptools
        pip install tox
        tox run -e min_versions
    - name: JUnit Report Action
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: 'reports/pytest-*.xml'
    - name: Upload to codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
        files: ./reports/coverage-*.xml
        flags: pytest
        name: "TMD-py${{ matrix.python-version }}"
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: tests-${{ matrix.python-version }}
        retention-days: 4
        path: |
          .tox/py*/tmp
          docs/build
          reports
