name: Run all tox jobs using Python3

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install tox-gh-actions
    - name: Run tox
      run: |
        tox
    - name: JUnit Report Action
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: 'reports/pytest-*.xml'
    - name: Upload to codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
        files: ./reports/coverage-*.xml
        flags: pytest
        name: "TMD-py${{ matrix.python-version }}"
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: tests-${{ matrix.python-version }}
        retention-days: 4
        path: |
          .tox/py*/tmp
          docs/build
          reports
